name: Rust CI/CD Pipeline
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  CARGO_TERM_COLOR: always
jobs:
  check-and-test:
    name: Code Quality & Tests (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Linux install llvm
      - name: Install LLVM 22 (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y lsb-release wget software-properties-common gnupg
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 22 all
          sudo ln -s /usr/lib/llvm-22/bin/llvm-config /usr/bin/llvm-config
          echo "LLVM_SYS_221_PREFIX=/usr/lib/llvm-22" >> $GITHUB_ENV
          echo "/usr/lib/llvm-22/bin" >> $GITHUB_PATH

      # MacOS install llvm
      - name: Install LLVM 22 (MacOS)
        if: matrix.os == 'macos-latest'
        shell: bash
        env:
          HOMEBREW_NO_REQUIRE_TAP_TRUST: 1
          HOMEBREW_NO_ENV_HINTS: 1
        run: |
          brew install llvm@22 lld
          echo "LLVM_SYS_221_PREFIX=$(brew --prefix llvm@22)" >> $GITHUB_ENV
          echo "$(brew --prefix llvm@22)/bin" >> $GITHUB_PATH
          echo "CPPFLAGS=-I/opt/homebrew/opt/llvm/include" >> $GITHUB_ENV
          echo "LDFLAGS=-L/opt/homebrew/opt/llvm/lib" >> $GITHUB_ENV
          echo "CMAKE_PREFIX_PATH=/opt/homebrew/opt/llvm" >> $GITHUB_ENV

      # Windows install llvm
      - name: Install LLVM 22 (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          choco install llvm --version=22.1.7 --no-progress
          $llvmRoot = "C:\Program Files\LLVM"
          $llvmBin = "$llvmRoot\bin"
          echo "LLVM_SYS_221_PREFIX=$llvmRoot" >> $env:GITHUB_ENV
          echo "$llvmBin" >> $env:GITHUB_PATH
          $env:PATH += ";$llvmBin"
          llvm-config --version
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - name: Cache Cargo registry and build artifacts
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ matrix.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ matrix.os }}-cargo-
      - name: Fetch dependencies
        run: cargo fetch
      - name: Auto format code and commit
        if: matrix.os == 'ubuntu-latest' && github.event_name == 'push'
        run: |
          cargo fmt --all
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          if ! git diff --quiet; then
            git add .
            git commit -m "chore: auto format code via CI"
            git push
          fi
      - name: Check code formatting
        run: cargo fmt --all -- --check
      - name: Run Clippy lints
        run: >
          cargo clippy --all-targets --all-features
          --
          -D warnings
          -A non_snake_case
          -A clippy::module_inception
          -A clippy::useless_format
          -A clippy::collapsible_if
      - name: Run tests
        run: cargo test --verbose